reorder_modules = true
max_width = 105
use_small_heuristics = "Default"

#struct_lit_width = 20
struct_lit_width = 22

#struct_variant_width = 40
struct_variant_width = 44

#single_line_if_else_max_width = 60