// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// This file contains code originally from rust-analyzer, licensed under Apache License 2.0.
// Modifications have been made to the original code.

//! Generated by `cargo testgen`, do not edit by hand.

use crate::resolve::check_resolve;

// language=Move
#[test]
fn test_resolve_loop_expr_label_for_break() {
    check_resolve(
        r#"
module 0x1::m {
    fun main() {
        'label: loop {
         //X
            break 'label;
                    //^
                   
        }
    }
}        
"#,
    )
}

// language=Move
#[test]
fn test_resolve_while_expr_label_for_continue() {
    check_resolve(
        r#"
module 0x1::m {
    fun main() {
        'label: while (true) {
         //X
            continue 'label;
                      //^
                   
        }
    }
}        
"#,
    )
}

// language=Move
#[test]
fn test_resolve_while_expr_label_for_break() {
    check_resolve(
        r#"
module 0x1::m {
    fun main() {
        'label: while (true) {
         //X
            break 'label;
                    //^
                   
        }
    }
}        
"#,
    )
}

// language=Move
#[test]
fn test_resolve_loop_expr_label_for_continue() {
    check_resolve(
        r#"
module 0x1::m {
    fun main() {
        'label: loop {
         //X
            continue 'label;
                      //^
                   
        }
    }
}        
"#,
    )
}
