module 0x1::match {
    fun t7_unqualified_variant() {
        match (self) {
            Some { value: Option::None } =
                                       //^ expected '=>'
        }
    }

    fun t8_unqualified_variant() {
        match (self) {
            Some { value: Option::None } =,
                                       //^ expected '=>'
            Some { value: Option::None } =
                                        //^ expected expression
                                        //^ expected SEMICOLON
                                        //^ expected R_CURLY
                                        //^ expected R_CURLY
