module 0x1::match {
    fun t7_unqualified_variant() {
        match (self) {
            Some { value: Option::None } =
                                      //^ expected FAT_ARROW
        }
    }

    fun t8_unqualified_variant() {
        match (self) {
            Some { value: Option::None } =,
                                      //^ expected FAT_ARROW
            Some { value: Option::None } =
                                      //^ expected SEMICOLON
                                       //^ unexpected token EQ
                                       //^ expected R_CURLY
                                       //^ expected R_CURLY
