module 0x1::assert_in_lambda {
    fun main(
        f: |Element, assert!, assert!(), call(| Element,
                         //^ expected COMMA
                         //^ expected type
                                  //^ expected COMMA
                                  //^ expected type
                                           //^ expected COMMA
                                            //^ expected R_PAREN
    ) {

    }
}
