module 0x1::invalid_use_in_block {
    fun main() {
        use use std::string::{Self, };
         //^ expected address or identifier
         //^ expected SEMICOLON
        use *;
          //^ expected address or identifier
        use
         //^ expected address or identifier
         //^ expected SEMICOLON
        use std::
               //^ expected identifier
               //^ expected SEMICOLON
        use std::;
               //^ expected identifier
        use std::string::
                       //^ expected identifier
                       //^ expected SEMICOLON
        use std::string::{}
                         //^ expected SEMICOLON
        use std::string::{a::}
                           //^ expected identifier
                            //^ expected SEMICOLON
        use std::string::{if};
                        //^^ expected identifier
        use std::string::{spec, ident};
                        //^^^^ expected identifier
        use std::string::{b"123"}
                        //^^^^^^ expected identifier
                               //^ expected SEMICOLON
    }
}
