module 0x1::item_recovery_let {
    fun main() {
        let
        let a
      //^^^ expected pattern
        let a:
        let a: u8
        let a: u8<>
        let a: u8<T,,>
        let a: u8 =
                 //^ expected expression
                 //^ expected SEMICOLON
        let a: u8 = 1
                   //^ expected SEMICOLON
        let a: vector<
                    //^ expected type argument
                    //^ expected R_ANGLE
                    //^ expected SEMICOLON
    }
}
