module 0x1
     //^^^ expected identifier, got '0x1'
     //^^^ expected '{'
module 0x1::
          //^ expected identifier, got 'module'
          //^ expected '{'
module 0x1::item
              //^ expected '{'
module std::item
              //^ expected '{'

module 0x1::item_recovery {
    unknown
  //^^^^^^^ expected an item, got IDENT
    enum
      //^ expected identifier, got 'fun'
    fun
     //^ expected identifier, got 'struct'
    struct
        //^ expected identifier, got 'spec'
        //^ expected `;`, `{`, or `(`
    spec
      //^ expected identifier
      //^ expected a block
    spec {}
      //^ expected identifier
    spec ref
          //^ expected a block
}
    unknown
  //^^^^^^^ unexpected ident 'unknown'
    script
        //^ expected `{`
    spec
    spec ref
  //^ expected identifier
  //^ expected '{'
          //^ expected '{'
    spec 0x1::ref


//< expected '{'
