module 0x1::item_recovery_fun_params {
    fun main(a, b, b:,, c::, d: u8+u8, e: u8) {}
            //^ expected type annotation
               //^ expected type annotation
                   //^ expected type
                    //^ expected value parameter
                       //^^ expected type annotation
                       //^^ expected COMMA
                       //^^ expected value parameter
                                //^ expected COMMA
                                //^ expected value parameter
}
