module 0x1
     //^^^ expected an identifier
     //^^^ expected `{`
module 0x1::
          //^ expected an identifier
          //^ expected `{`
module 0x1::item
              //^ expected `{`

module 0x1::item_recovery {
    unknown
  //^^^^^^^ expected an item, got IDENT
    enum
      //^ expected identifier, got 'fun'
    fun
     //^ expected identifier, got 'struct'
    struct
        //^ expected identifier, got 'spec'
        //^ expected `;`, `{`, or `(`
    spec
      //^ expected identifier
      //^ expected a block
    spec {}
      //^ expected identifier
    spec ref
          //^ expected a block
}
unknown
//< unexpected token IDENT
script
    //^ expected `{`
spec
spec ref
//< expected identifier
//< expected `{`
      //^ expected `{`
spec 0x1::ref


//< expected `{`
