module 0x1::item_recovery_let {
    fun main() {
        let
         //^ expected pattern
         //^ expected SEMICOLON
        let a
           //^ expected SEMICOLON
        let a:
            //^ expected type
            //^ expected SEMICOLON
        let a: u8
               //^ expected SEMICOLON
        let a: u8<>
                 //^ expected SEMICOLON
        let a: u8<T,,>
                  //^ expected type argument
                    //^ expected SEMICOLON
        let a: u8 =
                 //^ expected expression
                 //^ expected SEMICOLON
        let a: u8 = 1
                   //^ expected SEMICOLON
        let a: vector<
                    //^ expected type argument
                    //^ expected R_ANGLE
                    //^ expected SEMICOLON
    }
}
