module 0x1::let_invalid_ident_pat {
    fun main() {
        let option::some(
            option::some(
                WithdrawCapability {
                    expiration_sec: withdraw_proof.expiration_sec,
                                                //^ expected COMMA
                                                //^ expected identifier
                                                               //^ expected R_CURLY
                                                                //^ expected R_PAREN
                                                                //^ expected R_PAREN
                                                                //^ expected SEMICOLON
                }
            )
          //^ expected an item, got R_PAREN
    }
}
//< unexpected ident '}'
