module 0x1::struct_recovery {
    struct { }
        //^ expected an identifier
    struct <T> has
        //^ expected an identifier
                //^ expected ability
                //^ expected `;`, `{`, or `(`
    struct S has {}
              //^ expected ability
    struct S has copy,
                    //^ expected `;`, `{`, or `(`
    struct S has copy,, {}
                    //^ expected ability
    struct S { field: , field2: }
                   //^ expected type
                             //^ expected type
}
