module 0x1::value_arg_recovery {
    fun main() {
        call(1,,, 2+, &&&<>, err<, call[, assert!, |a| a +, |b| call() +, ..,);
             //^ expected argument
              //^ expected argument
                  //^ expected expression
                        //^ expected expression
                         //^ expected expression
                               //^ expected expression
                                      //^ expected R_BRACK
                                               //^ expected argument list
                                                        //^ expected expression
                                                                      //^ expected expression
    }
}
