name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --check

  rust_tests:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - run: cargo nextest run --hide-progress-bar --no-fail-fast

  check_diagnostics:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build aptos-analyzer binary with xtask
        run: cargo xtask install --server

      - name: Fetch aptos-core repository
        uses: actions/checkout@v4
        with:
          repository: aptos-labs/aptos-core
          path: aptos-core

      - name: Check diagnostics on aptos-core:move-stdlib
        run: aptos-analyzer check --kinds error -- ./aptos-core/aptos-move/framework/move-stdlib

      - name: Check diagnostics on aptos-core:aptos-stdlib
        run: aptos-analyzer check --kinds error -- ./aptos-core/aptos-move/framework/aptos-stdlib

      # todo: aptos-framework

      - name: Check diagnostics on aptos-core:aptos-experimental
        run: aptos-analyzer check --kinds error -- ./aptos-core/aptos-move/framework/aptos-experimental

      - name: Check diagnostics on aptos-core:aptos-token
        run: aptos-analyzer check --kinds error -- ./aptos-core/aptos-move/framework/aptos-token

      - name: Check diagnostics on aptos-core:aptos-token-objects
        run: aptos-analyzer check --kinds error -- ./aptos-core/aptos-move/framework/aptos-token-objects

  build_vsix:
    name: Build .vsix extension
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install xvfb
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y xvfb

      - run: npm ci
        working-directory: ./editors/code

      - run: npm run package --scripts-prepend-node-path
        working-directory: ./editors/code
