name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --check

  rust_tests:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98

      - run: cargo nextest run --hide-progress-bar --no-fail-fast

  check_diagnostics:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build aptos-language-server binary with xtask
        run: cargo xtask install --server

      - name: Fetch aptos-core repository
        uses: actions/checkout@v4
        with:
          repository: aptos-labs/aptos-core
          path: aptos-core

      - name: Check diagnostics on aptos-core:framework
        run: aptos-language-server diagnostics --kinds error -- ./aptos-core/aptos-move/framework

      - name: Install aptos-cli
        uses: WGB5445/aptos-cli-setup@v1
        with:
          version: "7.7.0"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache ~/.move directory
        uses: actions/cache@v4
        with:
          path: ~/.move
          key: ${{ runner.os }}-dot-move

      - name: Fetch liquidswap repository
        uses: actions/checkout@v4
        with:
          repository: pontem-network/liquidswap
          path: liquidswap

      - name: Fetch liquidswap dependencies
        working-directory: ./liquidswap
        run: aptos move compile --fetch-deps-only

      - name: Check diagnostics on liquidswap
        run: aptos-language-server diagnostics --kinds error -- ./liquidswap

      - name: Fetch daily-move repository
        uses: actions/checkout@v4
        with:
          repository: aptos-labs/daily-move
          path: daily-move

      - name: Fetch daily-move dependencies (1)
        working-directory: ./daily-move/snippets/fractional-token
        run: aptos move compile --fetch-deps-only --dev

      - name: Fetch daily-move dependencies (2)
        working-directory: ./daily-move/snippets/liquid-nfts
        run: aptos move compile --fetch-deps-only --dev

      - name: Check diagnostics on daily-move
        run: aptos-language-server diagnostics --kinds error -- ./daily-move

  build_vsix:
    name: Build .vsix extension
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install xvfb
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y xvfb

      - run: npm ci
        working-directory: ./editors/code

      - run: npm run package --scripts-prepend-node-path
        working-directory: ./editors/code
