name: CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    changes:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
        outputs:
            typescript: ${{ steps.filter.outputs.typescript }}
        steps:
            -   uses: actions/checkout@v4
            -   uses: dorny/paths-filter@1441771bbfdd59dcd748680ee64ebd8faab1a242
                id: filter
                with:
                    filters: |
                        typescript:
                          - 'editors/code/**'

    rust_tests:
        strategy:
            matrix:
                platform: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Rust toolchain
                uses: dtolnay/rust-toolchain@stable

            -   name: Build aptos-analyzer binary with xtask
                run: cargo xtask install --server

    typescript:
        needs: changes
        if: needs.changes.outputs.typescript == 'true'
        name: TypeScript
        strategy:
            matrix:
                platform: [ ubuntu-latest, windows-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Install Nodejs
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install xvfb
                if: matrix.os == 'ubuntu-latest'
                run: sudo apt-get install -y xvfb

            -   run: npm ci
                working-directory: ./editors/code

            -   run: npm run package --scripts-prepend-node-path
                working-directory: ./editors/code
